from dotenv import load_dotenv
import os
load_dotenv()
api=os.getenv('API_URL')
db=os.getenv('DB_PATH')
log=os.getenv('LOG_FILE')
retry=int(os.getenv('RETRY_ATTEMPTS'))
access_key=os.getenv('AWS_ACCESS_KEY_ID')
secret_key=os.getenv('AWS_SECRET_ACCESS_KEY')
bucket_name=os.getenv('AWS_BUCKET_NAME')
region=os.getenv('AWS_REGION')
pg_host=os.getenv('PG_HOST')
pg_port=os.getenv('PG_PORT')
pg_database=os.getenv('PG_DATABASE')
pg_user=os.getenv('PG_USER')
pg_password=os.getenv('PG_PASSWORD')